"""Add composite index for messages query optimization

Revision ID: f902e33d1a46
Revises: b03417887b93
Create Date: 2025-10-16 17:59:26.020866

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f902e33d1a46"
down_revision: str | Sequence[str] | None = "b03417887b93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_messages_user_deleted_created",
        "messages",
        ["user_id", "deleted_at", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_user_deleted_created", table_name="messages")
    # ### end Alembic commands ###
